#!/usr/bin/env bash
# This script was generated by bashly 1.3.8 (https://bashly.dev)
# Modifying it manually is not recommended

# :wrapper.bash3_bouncer
if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2))); then
  printf "bash version 4.2 or higher is required\n" >&2
  exit 1
fi

# :command.master_script
# :command.root_command
root_command() {
  # src/root_command.sh

  # Available keys
  keys=("short_form" "long_form" "desc" "meta" 'meta.type' 'meta.source' )

  selected_key=${args[--key]}
  item=${args[item]}
  file=${args[--file]}

  if [[ ${args[--verbose]} ]]; then
      verbose=true
  else
      verbose=false
  fi

  log "$item $file $selected_key"

  echo "$item : $(get_attribute)"

}

# :command.version_command
version_command() {
  echo "$version"
}

# :command.usage
cvdq_cli_usage() {
  printf "cvdq-cli - Traducteur d'acronymes et de sigles\n\n"

  printf "%s\n" "$(green_bold "Usage:")"
  printf "  cvdq-cli \033[0;31m ITEM \033[0m [OPTIONS]\n"
  printf "  cvdq-cli --help | -h\n"
  printf "  cvdq-cli --version\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    # :command.usage_options
    printf "%s\n" "$(green_bold "Options:")"

    # :command.usage_flags
    # :flag.usage
    printf "  %s\n" "$(red "--key, -k ATTRIBUTE")"
    printf "    Key of the attribute to look for in the .JSON file.\n"
    printf "    %s\n" "Default: $(cyan "desc")"
    echo

    # :flag.usage
    printf "  %s\n" "$(red "--verbose, -v")"
    printf "    Set verbose output to true\n"
    echo

    # :flag.usage
    printf "  %s\n" "$(red "--item, -i ITEM")"
    printf "    item to look for in the .JSON file\n"
    echo

    # :flag.usage
    printf "  %s\n" "$(red "--file, -f JSON")"
    printf "    .JSON file to load as a glossary.\n"
    printf "    %s\n" "Default: $(cyan "glossaire.json")"
    echo

    # :command.usage_fixed_flags
    printf "  %s\n" "$(red "--help, -h")"
    printf "    Show this help\n"
    echo
    printf "  %s\n" "$(red "--version")"
    printf "    Show version number\n"
    echo

    # :command.usage_args
    printf "%s\n" "$(green_bold "Arguments:")"

    # :argument.usage
    printf "  %s\n" "$(yellow "ITEM")"
    printf "    item to look for in the glossary\n"
    echo

    # :command.usage_environment_variables
    printf "%s\n" "$(green_bold "Environment Variables:")"

    # :environment_variable.usage
    printf "  %s\n" "$(magenta "DEFAULT_GLOSSARY")"
    printf "    Set the default glossary file to \"glossaire.json\"\n"
    echo

    # :command.usage_examples
    printf "%s\n" "$(green_bold "Examples:")"
    printf "  cvdq-cli SNCF\n"
    printf "  cvdq-cli -f \"glossaire-reseau.json\" IETF\n"
    printf "  cvdq-cli -k desc IETF\n"
    printf "  cvdq-cli -h\n"
    echo

  fi
}

# :command.normalize_input
# :command.normalize_input_function
normalize_input() {
  local arg passthru flags
  passthru=false

  while [[ $# -gt 0 ]]; do
    arg="$1"
    if [[ $passthru == true ]]; then
      input+=("$arg")
    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^-([a-zA-Z0-9][a-zA-Z0-9]+)$ ]]; then
      flags="${BASH_REMATCH[1]}"
      for ((i = 0; i < ${#flags}; i++)); do
        input+=("-${flags:i:1}")
      done
    elif [[ "$arg" == "--" ]]; then
      passthru=true
      input+=("$arg")
    else
      input+=("$arg")
    fi

    shift
  done
}

# :command.inspect_args
inspect_args() {
  local k

  if ((${#args[@]})); then
    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
    echo args:
    for k in "${sorted_keys[@]}"; do
      echo "- \${args[$k]} = ${args[$k]}"
    done
  else
    echo args: none
  fi

  if ((${#deps[@]})); then
    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
    echo
    echo deps:
    for k in "${sorted_keys[@]}"; do
      echo "- \${deps[$k]} = ${deps[$k]}"
    done
  fi

  if ((${#env_var_names[@]})); then
    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
    echo
    echo "environment variables:"
    for k in "${sorted_names[@]}"; do
      echo "- \$$k = ${!k:-}"
    done
  fi
}

# :command.user_lib
# src/lib/colors.sh
enable_auto_colors() {
  if [[ -z ${NO_COLOR+x} && ! -t 1 ]]; then
    NO_COLOR=1
  fi
}

print_in_color() {
  local color="$1"
  shift
  if [[ "${NO_COLOR:-}" == "" ]]; then
    printf "$color%b\e[0m\n" "$*"
  else
    printf "%b\n" "$*"
  fi
}

red() { print_in_color "\e[31m" "$*"; }
green() { print_in_color "\e[32m" "$*"; }
yellow() { print_in_color "\e[33m" "$*"; }
blue() { print_in_color "\e[34m" "$*"; }
magenta() { print_in_color "\e[35m" "$*"; }
cyan() { print_in_color "\e[36m" "$*"; }
black() { print_in_color "\e[30m" "$*"; }
white() { print_in_color "\e[37m" "$*"; }

bold() { print_in_color "\e[1m" "$*"; }
underlined() { print_in_color "\e[4m" "$*"; }
bold_underlined() { print_in_color "\e[1;4m" "$*"; }

red_bold() { print_in_color "\e[1;31m" "$*"; }
green_bold() { print_in_color "\e[1;32m" "$*"; }
yellow_bold() { print_in_color "\e[1;33m" "$*"; }
blue_bold() { print_in_color "\e[1;34m" "$*"; }
magenta_bold() { print_in_color "\e[1;35m" "$*"; }
cyan_bold() { print_in_color "\e[1;36m" "$*"; }
black_bold() { print_in_color "\e[1;30m" "$*"; }
white_bold() { print_in_color "\e[1;37m" "$*"; }

red_underlined() { print_in_color "\e[4;31m" "$*"; }
green_underlined() { print_in_color "\e[4;32m" "$*"; }
yellow_underlined() { print_in_color "\e[4;33m" "$*"; }
blue_underlined() { print_in_color "\e[4;34m" "$*"; }
magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
black_underlined() { print_in_color "\e[4;30m" "$*"; }
white_underlined() { print_in_color "\e[4;37m" "$*"; }

# src/lib/get_attribute.sh
get_attribute(){

    # jq returns null if key absent (empty) ; -r to get raw string ; split the argument key "meta.type" in an array (splitted by dot '.') as ["meta","type"] ; Then reduce ARRAY[] as $p ( INIT; UPDATE )
    ATTR=$(jq -r --arg item "$item" --arg key $selected_key 'reduce ($key | split("."))[] as $p (.[$item]; if . == null then null else .[$p] end) // empty' "$file")

    if [ -z "$ATTR" ]; then
        echo "No output found for attribute '$selected_key' for item '$item'" >&2
        exit 1
    fi

    printf "%s\n" "$ATTR"

}

# src/lib/log.sh
log(){
    if [ "$verbose" == true ]; then
        echo $@
    fi
}

# :command.command_functions

# :command.parse_requirements
parse_requirements() {
  local key
  
  if [ "$#" -eq 0 ]; then
    cvdq_cli_usage
  fi

  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --version)
        version_command
        exit
        ;;

      --help | -h)
        long_usage=yes
        cvdq_cli_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.environment_variables_filter

  env_var_names+=("DEFAULT_GLOSSARY")

  # :command.command_filter
  action="root"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      # :flag.case
      --key | -k)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--key']="$2"
          shift
          shift
        else
          printf "%s\n" "--key requires an argument: --key, -k ATTRIBUTE" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --verbose | -v)

        # :flag.case_no_arg
        args['--verbose']=1
        shift
        ;;

      # :flag.case
      --item | -i)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--item']="$2"
          shift
          shift
        else
          printf "%s\n" "--item requires an argument: --item, -i ITEM" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --file | -f)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--file']="$2"
          shift
          shift
        else
          printf "%s\n" "--file requires an argument: --file, -f JSON" >&2
          exit 1
        fi
        ;;

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        # :argument.case
        if [[ -z ${args['item']+x} ]]; then
          args['item']=$1
          shift
        else
          printf "invalid argument: %s\n" "$key" >&2
          exit 1
        fi

        ;;

    esac
  done

  # :command.required_args_filter
  if [[ -z ${args['item']+x} ]]; then
    printf "missing required argument: ITEM\nusage: cvdq-cli ITEM [OPTIONS]\n" >&2

    exit 1
  fi

  # :command.default_assignments
  [[ -n ${args['--key']:-} ]] || args['--key']="desc"
  [[ -n ${args['--file']:-} ]] || args['--file']="glossaire.json"

}

# :command.initialize
initialize() {
  declare -g version="0.1.0"
  set -e

}

# :command.run
run() {
  # :command.globals
  declare -g long_usage=''
  declare -g -A args=()
  declare -g -A deps=()
  declare -g -a env_var_names=()
  declare -g -a input=()

  normalize_input "$@"
  parse_requirements "${input[@]}"

  case "$action" in
    "root") root_command ;;
  esac
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  # :command.start
  command_line_args=("$@")
  initialize
  run "${command_line_args[@]}"
fi
