#!/usr/bin/env bash
# This script was generated by bashly 1.3.8 (https://bashly.dev)
# Modifying it manually is not recommended

# :wrapper.bash3_bouncer
if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2))); then
  printf "bash version 4.2 or higher is required\n" >&2
  exit 1
fi

# :command.master_script
# :command.root_command
root_command() {
  # src/root_command.sh

  # Variables
  # Available keys
  declare -g -A keys=("short_form" "long_form" "desc" "meta" 'meta.type' 'meta.source' )
  declare -g selected_key=${args[--key]}
  declare -g item=${args[--item]}

  if [[ -n "${args['FILE']:-}" ]]; then
      declare -g file=${args['FILE']}
  else
      declare -g file=$DEFAULT_GLOSSARY
  fi

  declare -g NEW_ITEM=${args['--add']}

  # #

  # #

  # #

  # # # Default settings
  # # selected_key=$default_selected_key
  # # DB=$default_file
  # # if [ "$#" -eq 1 ]; then
  # #     ABBR="$1"
  # # fi
  # #

  # # while getopts "hf:i:k:v" opt; do
  # #     case $opt in
  # #         f)
  # #             DB=$OPTARG
  # #             ;;
  # #         h)
  # #             show_usage
  # #             exit 0
  # #             ;;
  # #         i)
  # #             ABBR=$OPTARG
  # #             ;;
  # #         k)
  # #             selected_key=$OPTARG
  # #             ;;
  # #         v)
  # #             verbose=true
  # #             log "Verbose mode enabled"
  # #             ;;
  # #         *)
  # #             show_usage
  # #             exit 1
  # #             ;;
  # #     esac
  # # done
  # # shift $((OPTIND - 1))
  # #

  # #

  # # # Verifications
  # #

  # # if [[ -v ABBR ]]; then
  # #     log "ABBR aldready defined."
  # # else
  # #     log "Item $1 will be searched."
  # #     ABBR=$1
  # # fi
  # #

  # #

  # # if [ -f "$DB" ]; then
  # #     log "Input file $DB will be used as a glossary."
  # # else
  # #     log "Error: Glossary file not found: $DB" >&2
  # #     exit 3
  # # fi
  # #

  # # for key in "${keys[@]}"; do
  # #     if [ "$selected_key" == "$key" ]; then
  # #         log "Selected key $selected_key will be used as a key."
  # #         valid_key=true
  # #     fi
  # # done
  # #

  # # if [ ! "$valid_key" == true ]; then
  # #     log "Error: $selected_key is not a valid key. Valid keys: $keys"
  # #     exit 2
  # # fi
  # #

  # # echo "$ABBR : $(get_attribute "$ABBR" "$DB")"

  if [[ ${args[--verbose]} ]]; then
      verbose=true
  else
      verbose=false
  fi

  log "$item $file $selected_key"

  if [[ ${args[--remote]} ]]; then
      remote_json
      exit 0
  fi

  if [[ ${args[--format]} ]]; then
      format_json
      echo "$file is formatted."
      exit 0
  fi

  if [[ ${args[--sort]} ]]; then
      sort_json
      echo "$file is sorted"
      exit 0
  fi

  if [[ ${args[--add]} ]]; then
      add_entry
      echo "$NEW_ITEM is added to $file"
      exit 0
  fi

  if [[ ${args[--item]} ]]; then
      print_attribute
      exit 0
  fi

}

# :command.version_command
version_command() {
  echo "$version"
}

# :command.usage
cvdq_cli_usage() {
  printf "cvdq-cli - Traducteur d'acronymes et de sigles\n\n"

  printf "%s\n" "$(green_bold "Usage:")"
  printf "  cvdq-cli [FILE] [OPTIONS]\n"
  printf "  cvdq-cli --help | -h\n"
  printf "  cvdq-cli --version\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    # :command.usage_options
    printf "%s\n" "$(green_bold "Options:")"

    # :command.usage_flags
    # :flag.usage
    printf "  %s\n" "$(red "--add, -a NEW_ITEM")"
    printf "    New Item to add in FILE\n"
    echo

    # :flag.usage
    printf "  %s\n" "$(red "--key, -k KEY")"
    printf "    Key of the attribute to look for in the .JSON file\n"
    printf "    %s\n" "Default: desc"
    echo

    # :flag.usage
    printf "  %s\n" "$(red "--verbose, -v")"
    printf "    Set verbose output to true\n"
    echo

    # :flag.usage
    printf "  %s\n" "$(red "--item, -i ITEM")"
    printf "    item to look for in the .JSON file\n"
    echo

    # :flag.usage
    printf "  %s\n" "$(red "--sort, -s")"
    printf "    Sort the .JSON\n"
    echo

    # :flag.usage
    printf "  %s\n" "$(red "--format, -f")"
    printf "    Format the FILE in the expected .JSON format\n"
    echo

    # :flag.usage
    printf "  %s\n" "$(red "--remote, -r")"
    printf "    Specify the remote JSON file to work with\n"
    printf "    %s\n" "Needs: --item"
    printf "    %s\n" "Conflicts: --sort, --format, --add"
    echo

    # :command.usage_fixed_flags
    printf "  %s\n" "$(red "--help, -h")"
    printf "    Show this help\n"
    echo
    printf "  %s\n" "$(red "--version")"
    printf "    Show version number\n"
    echo

    # :command.usage_args
    printf "%s\n" "$(green_bold "Arguments:")"

    # :argument.usage
    printf "  %s\n" "$(yellow "FILE")"
    printf "    .JSON file to load as a glossary\n"
    echo

    # :command.usage_environment_variables
    printf "%s\n" "$(green_bold "Environment Variables:")"

    # :environment_variable.usage
    printf "  %s\n" "$(magenta "DEFAULT_GLOSSARY")"
    printf "    Set the default glossary file to \"glossaire.json\"\n"
    printf "    %s\n" "Default: json/glossaire.json"
    echo

    # :environment_variable.usage
    printf "  %s\n" "$(magenta "REMOTE_SOURCE")"
    printf "    Set the remote JSON source\n"
    printf "    %s\n" "Default: https://data.occitanie.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-occitanie-glossaire-sigles-acronymes/exports/json"
    echo

    # :command.usage_examples
    printf "%s\n" "$(green_bold "Examples:")"
    printf "  REMOTE_SOURCE=\"https://myurl.org/api/explore/catalog/datasets/glossaire-sigles-acronymes/exports/json\"\n  cvdq-cli -i IETF --remote\n"
    printf "  cvdq-cli \"glossaire-reseau.json\" -i IETF\n"
    printf "  cvdq-cli -k desc -i IETF\n"
    printf "  cvdq-cli --sort \"glossaire-reseau.json\" --verbose\n"
    printf "  cvdq-cli --add UNESCO\n"
    printf "  cvdq-cli --format \"glossaire-medecine.json\"\n"
    printf "  cvdq-cli -h\n"
    echo

  fi
}

# :command.normalize_input
# :command.normalize_input_function
normalize_input() {
  local arg passthru flags
  passthru=false

  while [[ $# -gt 0 ]]; do
    arg="$1"
    if [[ $passthru == true ]]; then
      input+=("$arg")
    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^-([a-zA-Z0-9][a-zA-Z0-9]+)$ ]]; then
      flags="${BASH_REMATCH[1]}"
      for ((i = 0; i < ${#flags}; i++)); do
        input+=("-${flags:i:1}")
      done
    elif [[ "$arg" == "--" ]]; then
      passthru=true
      input+=("$arg")
    else
      input+=("$arg")
    fi

    shift
  done
}

# :command.inspect_args
inspect_args() {
  local k

  if ((${#args[@]})); then
    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
    echo args:
    for k in "${sorted_keys[@]}"; do
      echo "- \${args[$k]} = ${args[$k]}"
    done
  else
    echo args: none
  fi

  if ((${#deps[@]})); then
    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
    echo
    echo deps:
    for k in "${sorted_keys[@]}"; do
      echo "- \${deps[$k]} = ${deps[$k]}"
    done
  fi

  if ((${#env_var_names[@]})); then
    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
    echo
    echo "environment variables:"
    for k in "${sorted_names[@]}"; do
      echo "- \$$k = ${!k:-}"
    done
  fi
}

# :command.user_lib
# src/lib/colors.sh
enable_auto_colors() {
  if [[ -z ${NO_COLOR+x} && ! -t 1 ]]; then
    NO_COLOR=1
  fi
}

print_in_color() {
  local color="$1"
  shift
  if [[ "${NO_COLOR:-}" == "" ]]; then
    printf "$color%b\e[0m\n" "$*"
  else
    printf "%b\n" "$*"
  fi
}

red() { print_in_color "\e[31m" "$*"; }
green() { print_in_color "\e[32m" "$*"; }
yellow() { print_in_color "\e[33m" "$*"; }
blue() { print_in_color "\e[34m" "$*"; }
magenta() { print_in_color "\e[35m" "$*"; }
cyan() { print_in_color "\e[36m" "$*"; }
black() { print_in_color "\e[30m" "$*"; }
white() { print_in_color "\e[37m" "$*"; }

bold() { print_in_color "\e[1m" "$*"; }
underlined() { print_in_color "\e[4m" "$*"; }
bold_underlined() { print_in_color "\e[1;4m" "$*"; }

red_bold() { print_in_color "\e[1;31m" "$*"; }
green_bold() { print_in_color "\e[1;32m" "$*"; }
yellow_bold() { print_in_color "\e[1;33m" "$*"; }
blue_bold() { print_in_color "\e[1;34m" "$*"; }
magenta_bold() { print_in_color "\e[1;35m" "$*"; }
cyan_bold() { print_in_color "\e[1;36m" "$*"; }
black_bold() { print_in_color "\e[1;30m" "$*"; }
white_bold() { print_in_color "\e[1;37m" "$*"; }

red_underlined() { print_in_color "\e[4;31m" "$*"; }
green_underlined() { print_in_color "\e[4;32m" "$*"; }
yellow_underlined() { print_in_color "\e[4;33m" "$*"; }
blue_underlined() { print_in_color "\e[4;34m" "$*"; }
magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
black_underlined() { print_in_color "\e[4;30m" "$*"; }
white_underlined() { print_in_color "\e[4;37m" "$*"; }

# src/lib/format_json.sh
format_json() {

    # Check if input .JSON file is correct
    jq -e . $file > /dev/null

    if [[ $? -ne 0 ]]; then
        log "File $file is not well formatted"
        exit 1
    fi

    tmp=$(mktemp)

    in=$file
    out=$tmp

    # Passe du format de data.occitanie.education.gouv.fr au format json attendu
    jq 'reduce .[] as $item ({};
        .[$item.sigle] = {
            long_form: $item.definition,
            desc: ($item.commentaire // $item.domaine),
            meta: {
                type: "undefined",
                source: "https://data.occitanie.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-occitanie-glossaire-sigles-acronymes/exports/json"
            }
        })' "$in" > "$out"

    jq -e . $out > /dev/null

    if [[ $? -ne 0 ]]; then
        log "File $file is not well formatted"
        exit 1
    else
        # Crée un backup
        mv $in $file.bkp

        # Remplace le fichier d'origine
        mv $out $in
    fi

}

# src/lib/get_attribute.sh
get_attribute(){

    # jq returns null if key absent (empty) ; -r to get raw string ; split the argument key "meta.type" in an array (splitted by dot '.') as ["meta","type"] ; Then reduce ARRAY[] as $p ( INIT; UPDATE )
    ATTR=$(jq -r --arg item "$item" --arg key "$1" 'reduce ($key | split("."))[] as $p (.[$item]; if . == null then null else .[$p] end) // empty' "$file")

    if [ -z "$ATTR" ]; then
        echo "No output found for attribute '$1' for item '$item'" >&2
        exit 1
    fi

    printf "%s\n" "$ATTR"
}

print_attribute(){
    echo "$item : $(get_attribute "long_form")"
    echo "$(get_attribute "desc")"

    if [[ "$selected_key" != "desc" && "$selected_key" != "long_form" ]]; then
        echo "$selected_key : $(get_attribute "$selected_key")"
    fi
}

set_attribute(){
    # TODO
    echo "TODO"
}

add_entry(){
        echo "=== Fichier : $(cyan "$file") <- Ajout de l'entrée : $(red "$NEW_ITEM") ==="
        read -rp "$(green long_form) : "    LONG_FORM ; keys['long_form']=$LONG_FORM
        read -rp "$(green desc) : "         DESC      ; keys['desc']=$DESC
        read -rp "$(green type) : "         TYPE      ; keys['meta.type']=$TYPE
        read -rp "$(green source) : "       SOURCE    ; keys['meta.source']=$SOURCE

        # Construit le JSON en échappant proprement les caractères spéciaux
        json=$(  jq -n \
            --arg key "$NEW_ITEM" \
            --arg long_form "${keys['long_form']}" \
            --arg desc "${keys['desc']}" \
            --arg type "${keys['meta.type']}" \
            --arg source "${keys['meta.source']}" \
            '{($key): {long_form: $long_form, desc: $desc, meta: {type: $type, source: $source}}}')

        if [[ -f "$file" ]]; then
            tmp="$(mktemp)"
            jq --argjson new "$json" '. * $new' "$file" > "$tmp"
            mv "$tmp" "$file"
            sort_json
            log "Ajout/merge effectué dans: $file"
        else
            echo "$json" > "$file"
            log "Fichier créé: $file"
        fi
        echo "Contenu ajouté:"
        echo "$json" | jq .
}

# src/lib/log.sh
log(){
    if [ "$verbose" == true ]; then
        echo $@
    fi
}

# src/lib/remote_json.sh
remote_json() {

    tmp_in=$(mktemp)
    tmp_out=$(mktemp)

    curl -s $REMOTE_SOURCE > $tmp_in

    # Passe du format de data.occitanie.education.gouv.fr au format json attendu
    jq 'reduce .[] as $item ({};
        .[$item.sigle] = {
            long_form: $item.definition,
            desc: ($item.commentaire // $item.domaine),
            meta: {
                type: "undefined",
                source: "https://data.occitanie.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-occitanie-glossaire-sigles-acronymes/exports/json"
            }
        })' "$tmp_in" > "$tmp_out"

    jq -e . $tmp_out > /dev/null

    if [[ $? -ne 0 ]]; then
        log "Remote file $REMOTE_SOURCE is not well formatted"
        exit 1
    else
        file=$tmp_out
        print_attribute
        rm $tmp_out $tmp_in
    fi

}

# src/lib/show_usage.sh
# Legacy show usage (homeade, not bashly-generated)
show_usage(){
    echo -e "Usage : $0 [OPTION]... \033[0;31m ITEM \033[0m";
    echo -e "\t -h       \t Show this message"
    echo -e "\t -i \033[0;31m ITEM \033[0m \t Look for \033[0;31m ITEM \033[0m"
    echo -e "\t -f \033[0;31m FILE \033[0m \t Use \033[0;31m FILE \033[0m as glossary (default : glossaire.json)"
    echo -e "\t -k \033[0;31m KEY  \033[0m \t Use \033[0;31m KEY \033[0m as attribute to look for (default : desc)"
    echo -e "\t -v      \t Enable verbose mode \n"
    echo -e "List of valid \033[0;31m KEY  \033[0m :"
    for key in ${keys[@]}; do
        echo -e "\t \033[0;35m $key \033[0m"
    done
    exit 0;
}

# Custom cvdq_cli_usage ( bashly-generated + additionnal manual edits )
cvdq_cli_usage() {
  printf "cvdq-cli - Traducteur d'acronymes et de sigles\n\n"

  printf "%s\n" "$(green_bold "Usage:")"
  printf "  cvdq-cli [FILE] [OPTIONS]\n"
  printf "  cvdq-cli --help | -h\n"
  printf "  cvdq-cli --version\n"
  echo

  # :command.long_usage
  if [[ -n "$long_usage" ]]; then
    # :command.usage_options
    printf "%s\n" "$(green_bold "Options:")"

    # :command.usage_flags
    # :flag.usage
    printf "  %s\n" "$(red "--add, -a NEW_ITEM")"
    printf "    New Item to add in FILE\n"
    echo

    # :flag.usage
    printf "  %s\n" "$(red "--key, -k KEY")"
    printf "    Key of the attribute to look for in the .JSON file\n"
    printf "    %s\n" "Default: $(cyan "desc")"
    echo

    # :flag.usage
    printf "  %s\n" "$(red "--verbose, -v")"
    printf "    Set verbose output to true\n"
    echo

    # :flag.usage
    printf "  %s\n" "$(red "--item, -i ITEM")"
    printf "    item to look for in the .JSON file\n"
    echo

    # :flag.usage
    printf "  %s\n" "$(red "--sort, -s")"
    printf "    Sort the .JSON\n"
    echo

    # :flag.usage
    printf "  %s\n" "$(red "--format, -f")"
    printf "    Format the $(yellow "FILE") in the expected .JSON format\n"
    echo

    # :command.usage_fixed_flags
    printf "  %s\n" "$(red "--help, -h")"
    printf "    Show this help\n"
    echo
    printf "  %s\n" "$(red "--version")"
    printf "    Show version number\n"
    echo

    # :command.usage_args
    printf "%s\n" "$(green_bold "Arguments:")"

    # :argument.usage
    printf "  %s\n" "$(yellow "FILE")"
    printf "    .JSON file to load as a glossary\n"
    printf "    %s\n" "Default: $(cyan glossaire.json)"
    echo

    # :command.usage_environment_variables
    printf "%s\n" "$(green_bold "Environment Variables:")"

    # :environment_variable.usage
    printf "  %s\n" "$(magenta "DEFAULT_GLOSSARY")"
    printf "    Set the default glossary file to \"$(cyan "glossaire.json")\"\n"
    echo

    # :command.usage_examples
    printf "%s\n" "$(green_bold "Examples:")"
    printf "  cvdq-cli \"$(cyan "glossaire-reseau.json")\" -i $(red "IETF")\n"
    printf "  cvdq-cli -k $(cyan desc) -i $(red "IETF")\n"
    printf "  cvdq-cli --sort \"$(cyan "glossaire-reseau.json")\" --verbose\n"
    printf "  cvdq-cli --add $(red "UNESCO")\n"
    printf "  cvdq-cli --format \"$(cyan "glossaire-medecine.json")\"\n"
    printf "  cvdq-cli -h\n"
    echo

  fi
}

# src/lib/sort_json.sh
# Trier par ordre alphabétique
sort_json(){
    # Check if .JSON file is correct
    jq -e . $file > /dev/null

    if [[ $? -ne 0 ]]; then
        exit 1
    fi

    tmp=$(mktemp)

    jq '
    to_entries
    | map(. as $e
          | {
              e: $e,
              sortkey: ($e.key
                | gsub("é";"e")
                | gsub("è";"e")
                | gsub("ê";"e")
                | gsub("ë";"e")
                | gsub("à";"a")
                | gsub("â";"a")
                | gsub("ä";"a")
                | gsub("ç";"c")
                | gsub("î";"i")
                | gsub("ï";"i")
                | gsub("ô";"o")
                | gsub("ö";"o")
                | gsub("ù";"u")
                | gsub("û";"u")
                | gsub("ü";"u")
                | gsub("É";"E")
                | gsub("È";"E")
                | gsub("Ê";"E")
                | gsub("Ë";"E")
                | gsub("À";"A")
                | gsub("Â";"A")
                | gsub("Ä";"A")
                | gsub("Ç";"C")
                | gsub("Î";"I")
                | gsub("Ï";"I")
                | gsub("Ô";"O")
                | gsub("Ö";"O")
                | gsub("Ù";"U")
                | gsub("Û";"U")
                | gsub("Ü";"U")
              )
            })
    | sort_by(.sortkey, (.e.key))
    | map(.e)
    | from_entries
    ' "$file" > "$tmp"
    mv "$tmp" "$file"
}

# :command.command_functions

# :command.parse_requirements
parse_requirements() {
  local key

  # :command.fixed_flags_filter
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --version)
        version_command
        exit
        ;;

      --help | -h)
        long_usage=yes
        cvdq_cli_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  # :command.environment_variables_filter
  # :command.environment_variables_default
  export DEFAULT_GLOSSARY="${DEFAULT_GLOSSARY:-json/glossaire.json}"
  export REMOTE_SOURCE="${REMOTE_SOURCE:-https://data.occitanie.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-occitanie-glossaire-sigles-acronymes/exports/json}"

  env_var_names+=("DEFAULT_GLOSSARY")
  env_var_names+=("REMOTE_SOURCE")

  # :command.command_filter
  action="root"

  # :command.parse_requirements_while
  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      # :flag.case
      --add | -a)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--add']="$2"
          shift
          shift
        else
          printf "%s\n" "--add requires an argument: --add, -a NEW_ITEM" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --key | -k)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--key']="$2"
          shift
          shift
        else
          printf "%s\n" "--key requires an argument: --key, -k KEY" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --verbose | -v)

        # :flag.case_no_arg
        args['--verbose']=1
        shift
        ;;

      # :flag.case
      --item | -i)

        # :flag.case_arg
        if [[ -n ${2+x} ]]; then
          args['--item']="$2"
          shift
          shift
        else
          printf "%s\n" "--item requires an argument: --item, -i ITEM" >&2
          exit 1
        fi
        ;;

      # :flag.case
      --sort | -s)

        # :flag.case_no_arg
        args['--sort']=1
        shift
        ;;

      # :flag.case
      --format | -f)

        # :flag.case_no_arg
        args['--format']=1
        shift
        ;;

      # :flag.case
      --remote | -r)
        # :flag.conflicts
        for conflict in --sort --format --add; do
          if [[ -n "${args[$conflict]:-}" ]]; then
            printf "conflicting options: %s cannot be used with %s\n" "$key" "$conflict" >&2
            exit 1
          fi
        done

        # :flag.case_no_arg
        args['--remote']=1
        shift
        ;;

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)
        # :command.parse_requirements_case
        # :command.parse_requirements_case_simple
        # :argument.case
        if [[ -z ${args['FILE']+x} ]]; then
          args['FILE']=$1
          shift
        else
          printf "invalid argument: %s\n" "$key" >&2
          exit 1
        fi

        ;;

    esac
  done

  # :command.needy_flags_filter
  # :flag.needs
  if [[ -n ${args['--remote']+x} ]] && [[ -z "${args[--item]:-}" ]]; then
    printf "%s\n" "--remote needs --item" >&2
    exit 1
  fi

  # :command.default_assignments
  [[ -n ${args['--key']:-} ]] || args['--key']="desc"

}

# :command.initialize
initialize() {
  declare -g version="1.2.0"
  set -e

  # :command.environment_variables_default
  export DEFAULT_GLOSSARY="${DEFAULT_GLOSSARY:-json/glossaire.json}"
  export REMOTE_SOURCE="${REMOTE_SOURCE:-https://data.occitanie.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-occitanie-glossaire-sigles-acronymes/exports/json}"

}

# :command.run
run() {
  # :command.globals
  declare -g long_usage=''
  declare -g -A args=()
  declare -g -A deps=()
  declare -g -a env_var_names=()
  declare -g -a input=()

  normalize_input "$@"
  parse_requirements "${input[@]}"

  case "$action" in
    "root") root_command ;;
  esac
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  # :command.start
  command_line_args=("$@")
  initialize
  run "${command_line_args[@]}"
fi
